### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by qcha41** [autolab-project/autolab#1]
[Ideas to discuss / to approve]
- [ ] remove get_driver shortcut function
- [ ] In user home folder, organize devices in folders containing a profile.ini file rather than setting everything in a general devices_config.ini file

[To do in ~order]
- [ ] add additional custom drivers path feature. Provide path in \home\autolab\drivers\additional_paths.txt 
- [ ] make DriverInfos self sufficient (no need to go deeper into Releases objects) = add shortcut methods in class DriverInfos (connect, help) last version by default but version can be specified
- [ ] implement Devices
- [ ] Implement Experiments
- [ ] Implement GUI

[OLD, to clean]
- [ ] Find a way to create the local folder during the package installation with pip
- [ ] autolab.close_all_devices()
- [ ] Fix the error appearing sometimes when the GUI is launched with the shell command 'autolab'. 
- [ ] Develop 3D display in GUI Scanner
- [ ] Develop GUI Histograms
- [ ] Develop multidimensions scans
- [ ] Add curve style options

**Comment by Python-simulation** [comment]
Need to discuss new features from scratch
